#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_ROOT="$(cd "$AGENTS_DIR/.." && pwd)"

source "$SCRIPT_DIR/_lib.sh"

SRC="$AGENTS_DIR/codex"
SKILLS_SRC="$AGENTS_DIR/skills"
TARGET="$WORKSPACE_ROOT/.codex"
SHARED_SKILLS_TARGET="$WORKSPACE_ROOT/.agents/skills"

mkdir -p "$TARGET/agents" "$SHARED_SKILLS_TARGET"

# Agent TOMLs — merge-safe (preserve foreign .toml files).
sync_dir_files "$SRC/agents" "$TARGET/agents" '*.toml'

# Build .codex/config.toml: concatenate the config fragments, then register
# every agentsync-owned agent as a spawnable role.
#
# Codex (>= 0.137) does NOT auto-discover standalone .codex/agents/*.toml — a
# role is only spawnable when it is declared in config.toml under [agents.<name>]
# with a config_file pointing at its definition (and only when the project is
# trusted). Generating the registrations here is what makes the agents usable;
# without them `spawn_agent` reports "unknown agent_type".
: > "$TARGET/config.toml"
for cfg in "$SRC/configs/"*.toml; do
    [[ -f "$cfg" ]] || continue
    cat "$cfg" >> "$TARGET/config.toml"
    echo "" >> "$TARGET/config.toml"
done

agent_files=()
for f in "$SRC/agents/"*.toml; do
    [[ -f "$f" ]] && agent_files+=("$f")
done
if [[ ${#agent_files[@]} -gt 0 ]]; then
    {
        echo "# --- Agent role registrations (generated by sync_codex.sh) ---"
        echo "# Source of truth is agents/codex/agents/*.toml. Codex spawns only the"
        echo "# roles declared below; it does not scan .codex/agents/ on its own."
    } >> "$TARGET/config.toml"
    for f in "${agent_files[@]}"; do
        base="$(basename "$f" .toml)"
        # name = the spawnable agent_type; falls back to the filename.
        name="$(sed -n 's/^name[[:space:]]*=[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' "$f" | head -1 || true)"
        [[ -n "$name" ]] || name="$base"
        # Reuse the agent's own description line verbatim (already valid TOML).
        descline="$(grep -m1 '^description[[:space:]]*=' "$f" || true)"
        {
            echo ""
            echo "[agents.$name]"
            [[ -n "$descline" ]] && echo "$descline"
            # config_file resolves relative to this config.toml's dir (.codex/).
            echo "config_file = \"agents/$base.toml\""
        } >> "$TARGET/config.toml"
    done
fi

# Skills go to .agents/skills/ (Codex/OpenCode shared location).
# Strip Claude-only frontmatter keys so Codex can parse them. Merge-safe: only
# prune/replace agentsync-owned skill dirs; preserve foreign skills.
owned_skills=()
if [[ -d "$SKILLS_SRC" ]]; then
    for skill_dir in "$SKILLS_SRC"/*; do
        [[ -d "$skill_dir" && -f "$skill_dir/SKILL.md" ]] || continue
        is_delegator_skill "$skill_dir/SKILL.md" && continue
        owned_skills+=("$(basename "$skill_dir")")
    done
fi
sync_prune_owned "$SHARED_SKILLS_TARGET" ${owned_skills[@]+"${owned_skills[@]}"}

if [[ -d "$SKILLS_SRC" ]]; then
    for skill_dir in "$SKILLS_SRC"/*; do
        [[ -d "$skill_dir" && -f "$skill_dir/SKILL.md" ]] || continue
        if is_delegator_skill "$skill_dir/SKILL.md"; then
            continue
        fi
        name="$(basename "$skill_dir")"
        rm -rf "${SHARED_SKILLS_TARGET:?}/$name"
        mkdir -p "$SHARED_SKILLS_TARGET/$name"
        for entry in "$skill_dir"/*; do
            base="$(basename "$entry")"
            [[ "$base" == "SKILL.md" ]] && continue
            cp -R "$entry" "$SHARED_SKILLS_TARGET/$name/"
        done
        normalize_skill < "$skill_dir/SKILL.md" > "$SHARED_SKILLS_TARGET/$name/SKILL.md"
    done
fi

if [[ -f "$AGENTS_DIR/AGENTS.md" ]]; then
    cp -f "$AGENTS_DIR/AGENTS.md" "$TARGET/AGENTS.md"
fi

echo "Synced .codex/ and .agents/skills/"
