#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENTS_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKSPACE_ROOT="$(cd "$AGENTS_DIR/.." && pwd)"

source "$SCRIPT_DIR/_lib.sh"

[[ -f "$AGENTS_DIR/agentsync.conf" ]] && source "$AGENTS_DIR/agentsync.conf"
# Codex auto-discovers standalone .codex/agents/*.toml. Older Codex releases
# only spawned roles declared under [agents.<name>] in config.toml — set
# CODEX_REGISTER_ROLES="yes" to also write those registrations.
CODEX_REGISTER_ROLES="${CODEX_REGISTER_ROLES:-no}"

SRC="$AGENTS_DIR/codex"
SKILLS_SRC="$AGENTS_DIR/skills"
TARGET="$WORKSPACE_ROOT/.codex"
SHARED_SKILLS_TARGET="$WORKSPACE_ROOT/.agents/skills"

mkdir -p "$TARGET/agents" "$SHARED_SKILLS_TARGET"

# Agent TOMLs: generated from roles/, plus verbatim codex/agents/*.toml (which
# win on a name clash). Merge-safe: foreign .toml files are preserved.
stage="$(stage_agents codex "$SRC/agents" '*.toml')"
sync_dir_files "$stage" "$TARGET/agents" '*.toml'

# .codex/config.toml = the config fragments, concatenated in name order.
: > "$TARGET/config.toml"
for cfg in "$SRC/configs/"*.toml; do
    [[ -f "$cfg" ]] || continue
    cat "$cfg" >> "$TARGET/config.toml"
    echo "" >> "$TARGET/config.toml"
done

if [[ "$CODEX_REGISTER_ROLES" == "yes" ]]; then
    {
        echo "# --- Agent role registrations (generated by sync_codex.sh) ---"
        echo "# For Codex releases that don't auto-discover .codex/agents/*.toml."
    } >> "$TARGET/config.toml"
    for f in "$stage"/*.toml; do
        [[ -f "$f" ]] || continue
        base="$(basename "$f" .toml)"
        name="$(sed -n 's/^name[[:space:]]*=[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' "$f" | head -1 || true)"
        [[ -n "$name" ]] || name="$base"
        descline="$(grep -m1 '^description[[:space:]]*=' "$f" || true)"
        {
            echo ""
            echo "[agents.$name]"
            [[ -n "$descline" ]] && echo "$descline"
            echo "config_file = \"agents/$base.toml\""
        } >> "$TARGET/config.toml"
    done
fi
rm -rf "$stage"

# Skills → .agents/skills/ (read by Codex, OpenCode, and Copilot). Frontmatter
# is reduced to the portable keys. codex/skills/<name> replaces a same-named
# shared skill for this target. Merge-safe: foreign skills are preserved.
sync_skills_normalized "$SKILLS_SRC" "$SHARED_SKILLS_TARGET" "$SRC/skills"

echo "Synced .codex/ and .agents/skills/"
